const {Sequelize,DataTypes}=require("sequelize");
module.exports=(sequelize)=>{
    const commEntity=sequelize.define("commEntity",{
        c_id:{
            type:DataTypes.INTEGER.UNSIGNED,
            primaryKey:true,
            autoIncrement:true
        },
        u_id:{
            type:DataTypes.STRING(255),
            allowNull:false,
            references:{
                model:"usersEntity",
                key:"u_id",
                onDelete:"CASCADE",
                onUpdate:"CASCADE"
            }
        },
        p_id:{
            type:DataTypes.INTEGER.UNSIGNED,
            allowNull:false,
            references:{
                model:"planEntity",
                key:"p_id",
                onDelete:"CASCADE",
                onUpdate:"CASCADE"
            }
        },
        post_time:{
            type:DataTypes.DATE,
            defaultValue:Sequelize.literal("CURRENT_TIMESTAMP")
        },
        update_time:{
            type:DataTypes.DATE,
            defaultValue:Sequelize.literal("CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP")
        },
        area:{
            type:DataTypes.ENUM('서울', '인천', '대전', '광주', '대구', '울산', '부산', '세종', '경기', '강원', '충북', '충남', '전북', '전남', '경북', '경남', '제주'),
            allowNull:false
        },
        title:{
            type:DataTypes.STRING(255)
        },
        content:{
            type:DataTypes.TEXT,
            allowNull:false
        },
        istj:{
            type:DataTypes.BOOLEAN,
            defaultValue:false,
        },
        istp:{
            type:DataTypes.BOOLEAN,
            defaultValue:false,
        },
        isfj:{
            type:DataTypes.BOOLEAN,
            defaultValue:false,
        },
        isfp:{
            type:DataTypes.BOOLEAN,
            defaultValue:false,
        },
        intj:{
            type:DataTypes.BOOLEAN,
            defaultValue:false,
        },
        intp:{
            type:DataTypes.BOOLEAN,
            defaultValue:false,
        },
        infj:{
            type:DataTypes.BOOLEAN,
            defaultValue:false,
        },
        infp:{
            type:DataTypes.BOOLEAN,
            defaultValue:false,
        },
        estj:{
            type:DataTypes.BOOLEAN,
            defaultValue:false,
        },
        estp:{
            type:DataTypes.BOOLEAN,
            defaultValue:false,
        },
        estj:{
            type:DataTypes.BOOLEAN,
            defaultValue:false,
        },
        estp:{
            type:DataTypes.BOOLEAN,
            defaultValue:false,
        },
        esfj:{
            type:DataTypes.BOOLEAN,
            defaultValue:false,
        },
        esfp:{
            type:DataTypes.BOOLEAN,
            defaultValue:false,
        },
        entj:{
            type:DataTypes.BOOLEAN,
            defaultValue:false,
        },
        entp:{
            type:DataTypes.BOOLEAN,
            defaultValue:false,
        },
        enfj:{
            type:DataTypes.BOOLEAN,
            defaultValue:false,
        },
        enfp:{
            type:DataTypes.BOOLEAN,
            defaultValue:false,
        }

    }, {
        timestamps: false,
        tableName: 'communitys' // 테이블 이름
    });
    return commEntity;
};